// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "CFluidTimerUI.h"
#include <conio.h>

void myFLTKCallBack(Fl_Widget * myWidget, void *)
{
	printf("Callback function called");

}



CFluidTimerUI::CFluidTimerUI()
{

	{
		m_win_timer = new Fl_Double_Window(462, 258);
		m_win_timer->user_data((void*)(this));

		{
			m_btn_start = new Fl_Button(25, 25, 65, 35, "Start");

			m_btn_start->callback(myFLTKCallBack);

			//Fl_Callback *objCallBk = &myFLTKCallBack;
			//m_btn_start->callback(objCallBk);
		} // Fl_Button* m_btn_start

		{
			m_btn_stop = new Fl_Button(115, 25, 65, 35, "Stop");
		} // Fl_Button* m_btn_stop

		m_win_timer->end();

	} // Fl_Double_Window* m_win_timer

}
