// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef CFluidTimerUI_h
#define CFluidTimerUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class CFluidTimerUI {
public:
  CFluidTimerUI();
  Fl_Double_Window *m_win_timer;
  Fl_Button *m_btn_start;
  Fl_Button *m_btn_stop;
};
#endif
